### ISSUE TITLE
Publish artifacts to Maven Central instead due to JCenter shutdown

### ISSUE THREAD

**Issue by zwessels** [ePages-de/restdocs-api-spec#153]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by klieber** [comment]
I'm working on doing the same for BerkleyTechnologyServices/restdocs-spec#116 but we will need restdocs-api-spec to be in central first.

**Comment by ozscheyge** [comment]
Thanks for reporting this @zwessels and @klieber !
We have this on the radar, but unfortunately I can't give an ETA, yet.

We'll probably discuss this internally within the next 1-2 weeks. I'll update this issue when I have more info.

**Comment by jmewes** [comment]
We have started to work on this.

**Comment by jmewes** [comment]
@otrosien,

I requested to create a Maven Central repository at Sonatype for "com.epages" so that we can publish "restdocs-api-spec" and "restdocs-wiremock" there. They answered that there is already a staging repository for the groupId "com.epages" and request that someone with the deployer role confirms that my request is legit (see https://issues.sonatype.org/browse/OSSRH-64798). Do you maybe know who created this staging repository?

**Comment by otrosien** [comment]
Could have been me, but I'm not sure. For sure my old epages email doesn't work anymore therefore I wouldn't be able to recover any accounts over there.

**Comment by jmewes** [comment]
> Could have been me, but I'm not sure. For sure my old epages email doesn't work anymore therefore I wouldn't be able to recover any accounts over there.

@otrosien ,

Thank you for your answer. Christian K. was able to confirm our Sonatype request.

**Comment by jmewes** [comment]
Version "0.11.2" is available on Maven Central.

![EPNG-7964__Use_Maven_Central_for_REST_Docs_API_Spec_by_jmewes_·_Pull_Request__439_·_ePages-de_ng-shared](https://user-images.githubusercontent.com/5235584/111459975-b24a1b80-871b-11eb-93a2-7ba7c5fb0c63.png)

**Comment by jmewes** [comment]
Done.
