### ISSUE TITLE
Allow to set type of ParameterDescriptor in WebTestClientRestDocumentationWrapper

### ISSUE THREAD

**Issue by jgazeau** [ePages-de/restdocs-api-spec#181]
Hello guys,

When using the WebTestClientRestDocumentationWrapper (which uses the RestDocumentationWrapper), it doesn't seems possible to enhance the snippets by setting a ParameterDescriptorWithType in the resourceDetails.
As when calling the `requestParameters()` method it only uses the input snippets, it will then instanciate ParameterDescriptorWithType with the default `SimpleType.STRING` type, wether or not we are already providing a ParameterDescriptorWithType with another `SimpleType` type.
https://github.com/ePages-de/restdocs-api-spec/blob/b4bd4bb89787af215b49a13264fa122df8f547b8/restdocs-api-spec/src/main/kotlin/com/epages/restdocs/apispec/RestDocumentationWrapper.kt#L51-L58

It could be possible to instanciate a ParameterDescriptorWithType and checking wether or not the initial ParameterDescriptor contains an attribute `parameterDescriptorType` (for example). Doing so, it will be more easy for users to set and manage the types of ParameterDescriptor (for example if they want to override it or set it to a specific value). 

WDYT ?

I've already create this [PR](https://github.com/ePages-de/restdocs-api-spec/pull/182) to solve it.

Regards,

Jordan.

**Comment by ozscheyge** [comment]
Hey Jordan,

Thanks for reaching out!

Unfortunately, I fail to see the problem. Afaik, we support specifying the type of ParameterDescriptors although Spring Restdocs does not. Via the new `ParameterDescriptorWithType` (hence the name), e.g.:

```
ParameterDescriptorWithType("describedParameter").type(SimpleType.BOOLEAN).description("description")
```

which then produces the correct type:

```
then(resourceSnippetJson.read<String>("request.requestParameters[0].name")).isEqualTo("describedParameter")
then(resourceSnippetJson.read<String>("request.requestParameters[0].type")).isEqualTo("BOOLEAN")
```

**Comment by jgazeau** [comment]
Hi Oliver, 

Thanks for your answer.
Indeed I might not have been really clear.

The problem is that when I am using the `document` method of the `WebTestClientRestDocumentationWrapper` to generate and enhance snippet, the generated snippets (`resource.json`) always contains parameter with type `STRING`. After investigating here is the process:

I use the  `document` method of the `WebTestClientRestDocumentationWrapper`:

https://github.com/ePages-de/restdocs-api-spec/blob/b4bd4bb89787af215b49a13264fa122df8f547b8/restdocs-api-spec-webtestclient/src/main/kotlin/com/epages/restdocs/apispec/WebTestClientRestDocumentationWrapper.kt#L11-L22

As input I provide the snippets from restdocs, and as resourceDetails I am providing a `ResourceSnippetDetails`, but if I put a `ParameterDescriptorWithType` in these `ResourceSnippetDetails` with a type different from `SimpleType.STRING`, it is not taken into account.

The method https://github.com/ePages-de/restdocs-api-spec/blob/b4bd4bb89787af215b49a13264fa122df8f547b8/restdocs-api-spec/src/main/kotlin/com/epages/restdocs/apispec/RestDocumentationWrapper.kt#L19 is using the method https://github.com/ePages-de/restdocs-api-spec/blob/b4bd4bb89787af215b49a13264fa122df8f547b8/restdocs-api-spec/src/main/kotlin/com/epages/restdocs/apispec/RestDocumentationWrapper.kt#L51-L58 based on this definition https://github.com/ePages-de/restdocs-api-spec/blob/b4bd4bb89787af215b49a13264fa122df8f547b8/restdocs-api-spec/src/main/kotlin/com/epages/restdocs/apispec/ResourceSnippetParameters.kt#L225-L228
So it uses the ParameterDescriptor from the snippets and not the ParameterDescriptorWithType I am providing in the resourceDetails. Because of that the ParameterDescriptorWithType are created, but always with the default type `SimpleType.STRING`.

I tought there were two possibilities:
* one is to change the `enhanceSnippetsWithResourceSnippet` to check wether or not ParameterDescriptorWithType are already provided in the resourceDetails and use them
* other one which seems much cleaner, was to modify the `ParameterDescriptorWithType` constructor based on the standard `ParameterDescriptor` from restdocs in which we could add an attribute to specify the type. (That's why I created the PR associated)

But maybe I'm doing something wrong ?

**Comment by jgazeau** [comment]
I've made a reproducer to make it more clear:

* branch [reproducer-181](https://github.com/jgazeau/restdocs-api-spec/tree/reproducer-181)
* test: [should_document_restdocs_and_resource_snippet_details_with_parameter_with_type](https://github.com/jgazeau/restdocs-api-spec/blob/reproducer-181/restdocs-api-spec-webtestclient/src/test/kotlin/com/epages/restdocs/apispec/WebTestClientRestDocumentationWrapperIntegrationTest.kt#L76) that specify `BOOLEAN` and  `NUMBER` typed parameter.
* generated snippet contains parameters with `STRING` type:
```json
...
  "request" : {
    "path" : "/some/{someId}/other/{otherId}",
    "method" : "POST",
    "contentType" : "application/json",
    "schema" : null,
    "headers" : [ ],
    "pathParameters" : [ {
      "name" : "someId",
      "attributes" : { },
      "description" : "someId",
      "ignored" : false,
      "type" : "STRING",
      "optional" : false
    }, {
      "name" : "otherId",
      "attributes" : { },
      "description" : "otherId",
      "ignored" : false,
      "type" : "STRING",
      "optional" : false
    } ],
...
```

**Comment by jgazeau** [comment]
Hello @ozscheyge , do you have any update on this issue ?
Regards,

**Comment by ozscheyge** [comment]
> Hello @ozscheyge , do you have any update on this issue ?
> Regards,

Hey @jgazeau ,

Sorry for the wait and thanks for the detailed motivation! I still have to get to it and will try to fit it in today!

**Comment by ozscheyge** [comment]
Hey @jgazeau ,

I got to it now, thanks to your detailed explanation and reproducer.

First, the problem is not just with `WebTestClientRestDocumentationWrapper`, but applies to the other wrappers and their document methods as well (`MockMvcRestDocumentationWrapper`, `RestAssuredRestDocumentationWrapper`).

The issue arose from how you used `resourceDetails` parameter in combination with `snippets` parameter:
https://github.com/jgazeau/restdocs-api-spec/blob/reproducer-181/restdocs-api-spec-webtestclient/src/test/kotlin/com/epages/restdocs/apispec/WebTestClientRestDocumentationWrapperIntegrationTest.kt#L296-L313
While I'm not 100% certain, why and when it makes sense to re-use snippets for `resourceDetails` (additional/better schema?), the main documentation needs to be in the snippets. Afaik, we introduced `resourceDetails` to pass further information on the request-response pair ("resource") which is needed for the targeted spec formats, but not provided by regular Spring REST Docs (e.g. summary and description for the entire resource).

I could solve the issue with Mathias' suggestion from https://github.com/ePages-de/restdocs-api-spec/issues/110#issuecomment-518119087 , by passing the `ResourceSnippetParameters` to the `resource` snippet:
https://github.com/ePages-de/restdocs-api-spec/pull/185/files#diff-672ed55d0ceac62de36f9aa7020d71ca27d6bbb03b9c0d7777699d21287191b5R298-R321
Note, that only providing `ResourceSnippetParametersBuilder` as `resourceDetails` parameter to the `document` method (without any further snippets) would not produce the desired documentation.

Would this approach solve your problem?

**Comment by jgazeau** [comment]
Hello @ozscheyge ,
Sorry for the delay. I understand the use of resourceDetails now. I'll make modifications on my side to provide a `ResourceSnippetParametersBuilder` directly to the `snippets` parameter as you suggest.
I'll close the PR and this issue.

Thank you very much for your help and time.
