### ISSUE TITLE
Allow separate RequestBody specifications for same path/method

### ISSUE THREAD

**Issue by dinosaur-guy** [ePages-de/restdocs-api-spec#210]
Hi,

I would like to document faulty requests as well as successful requests.
However it seems when generating the OpenAPI3 specification, all resources will be grouped under `request.path` (`resource.json`) and only one request definition is considered. Is it somehow possible to generate separate endpoints for the same path with different `requestBody` definitions?

**Comment by ozscheyge** [comment]
Hey @dinosaur-guy ,

yes, this should be possible. Are you using a distinct snippet name per request?

**Comment by ozscheyge** [comment]
Sounds like you are using it correctly.
Then, I'm afraid, this is by design of the OpenAPI3 generator then:
https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-openapi3-generator/src/test/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3GeneratorTest.kt#L111-L124

It discriminates based on path, content type and status code. It produces two examples but only a single schema for the request.

**Comment by dinosaur-guy** [comment]
OK, thats a pity. But thanks for your quick response!
